name = "iburuh-app"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "iburuh-db"
database_id = "d2565046-868c-4b06-a4a8-935284febe29"

[[env.production.kv_namespaces]]
binding = "SESSION"
id = "d080506692704b3e85ccec9d9dab0513"

[env.preview]
vars = { ENVIRONMENT = "preview" }

[[env.preview.d1_databases]]
binding = "DB"
database_name = "iburuh-db"
database_id = "d2565046-868c-4b06-a4a8-935284febe29"

[[env.preview.kv_namespaces]]
binding = "SESSION"
id = "d080506692704b3e85ccec9d9dab0513"
